- name: Do grub tasks
  when: ansible_architecture is match("x86.*")
  block:
    - name: Set grub default
      become: yes
      ini_file:
        path: /etc/default/grub
        section: null
        option: GRUB_DEFAULT
        value: "{{ avena_intel_grub_default }}"
        mode: '0644'
      notify: rebuild grub

    - name: Set grub timeout
      become: yes
      ini_file:
        path: /etc/default/grub
        section: null
        option: GRUB_TIMEOUT
        value: "{{ avena_intel_grub_timeout }}"
        mode: '0644'
      notify: rebuild grub

    - name: Set grub hidden timeout
      become: yes
      ini_file:
        path: /etc/default/grub
        section: null
        option: GRUB_HIDDEN_DEFAULT
        value: "{{ avena_intel_grub_hidden_timeout }}"
        mode: '0644'
      notify: rebuild grub
