- name: Run user tasks
  include_tasks:
    file: user.yml
    apply:
      tags: user
  tags: user

- name: Run updating tasks
  include_tasks:
    file: update.yml
    apply:
      tags: update
  tags: update

- name: Run naming tasks
  include_tasks:
    file: names.yml
    apply:
      tags: names
  tags: names

- name: Run ssh tasks
  include_tasks:
    file: ssh.yml
    apply:
      tags: ssh
  tags: ssh

- name: Run time tasks
  include_tasks:
    file: time.yml
    apply:
      tags: time
  tags: time

- name: Run networking tasks
  include_tasks:
    file: networking.yml
    apply:
      tags: networking
  tags: networking

- name: Run grub tasks
  include_tasks:
    file: grub.yml
    apply:
      tags: grub
  tags: grub

- name: Run dma tasks
  include_tasks:
    file: dma.yml
    apply:
      tags:
        - dma
