version: '3.1'
services:
  can_watchdog:
    build:
      context: ../can_watchdog
    restart: always
    environment:
      inactivity_threshold: 5
    volumes:
      - /var/run/dbus:/var/run/dbus:rw
      - /sys/class/net:/mnt/host/sys/class/net:ro
      - /sys/devices:/mnt/host/sys/devices:ro

volumes:
  can_watchdog:
