version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-gps-log:
    image: kafka-gps-log
    restart: always
    network_mode: host
    extra_hosts:
      kafka: 127.0.0.1
    environment:
      kafka_topic: "${gps_topic}"
  kafka-can-log:
    image: kafka-can-log
    restart: always
    network_mode: host
    extra_hosts:
      kafka: 127.0.0.1
    environment:
      can_dev: "${tra_interface}"
      kafka_topic: "${tra_interface}"
  engine-rpm-pub:
    image: engine-rpm-pub
    restart: always
    environment:
      isoblue_id: "${isoblue_id}"
      kafka_topic: "${tra_interface}"
      mqtt_topic: "${mqtt_topic}"
      cloud_domain: "${avena_domain}"
      mqtt_port: "${mqtt_port}"
      PYTHONUNBUFFERED: "1"
