- name: ensure distribution docker packages are not installed
  become: yes
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: ensure required packages for docker repository are installed
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: ensure docker apt key is installed
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

# TODO: Resolve "buster" correctly?
- name: ensure docker apt repository is installed
  become: yes
  apt_repository:
    repo: 'deb https://download.docker.com/linux/debian buster stable'
    state: present
    filename: docker

- name: ensure docker is installed
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: ensure docker group exists
  become: yes
  group:
    name: "{{ avena_docker_group }}"
    state: present

- name: ensure {{ ansible_user }} is part of the docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: "{{ avena_docker_group }}"
    append: yes
    state: present

- name: ensure docker is configured
  become: yes
  template:
    src: templates/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0600'
  notify: restart docker

- name: ensure python packages needed for docker-compose are installed
  become: yes
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - libffi-dev
      - libssl-dev
    state: present

- name: use pip to ensure docker-compose is installed
  command:
    cmd: python3 -m pip install -IU docker-compose
  become: yes
