- name: Run user tasks
  include_tasks:
    file: user.yml
    apply:
      tags:
        - user

- name: Run updating tasks
  include_tasks:
    file: update.yml
    apply:
      tags:
        - update

- name: Run naming tasks
  include_tasks:
    file: names.yml
    apply:
      tags:
        - names

- name: Run ssh tasks
  include_tasks:
    file: ssh.yml
    apply:
      tags:
        - ssh

- name: Run docker tasks
  include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker

- name: Run GPS and time sync tasks
  include_tasks:
    file: gps-time.yml
    apply:
      tags:
        - gps-time

- name: Run networking tasks
  include_tasks:
    file: networking.yml
    apply:
      tags:
        - networking

- name: Run intel tasks
  include_tasks:
    file: intel.yml
    apply:
      tags:
        - intel
  when: ansible_architecture matches("x86.*")

# TODO: Set  uboot to no delay booting
#- name: Run arm tasks
#  include_tasks:
#    file: arm.yml
#    apply:
#      tags:
#        - intel
#  when: ansible_architecture matches("arm*")
