version: '3.1'
services:
  gps2tsdb:
    build:
      context: ../gps2tsdb
    restart: always
    environment:
      db_user: "avena"
      db_host: "postgres"
      db_database: "avena"
      db_password: "password"
      db_port: "5432"
    depends_on:
      - postgres
#      - gps_verify
      - gps_replay
    volumes:
      - ../gps_replay/dbus:/var/run/dbus:rw

  gps_verify:
    build:
      context: ../gps_verify
    environment:
      db_user: "avena"
      db_host: "postgres"
      db_database: "avena"
      db_password: "password"
      db_port: "5432"

  gps_replay:
    build:
      context: ../gps_replay
    volumes:
#      - ../gps_replay/test_points.log:/opt/test_points.log
      - ../gps_replay/dbus:/var/run/dbus:rw

  postgres:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_DB: avena
      POSTGRES_PASSWORD: password
      POSTGRES_USER: avena
      TIMESCALEDB_TELEMETRY: "off"
    ports:
      - 5432:5432/tcp
    restart: always
#    volumes:
#      - postgres:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#volumes:
#  postgres: {}
